### PR TITLE
Add Turkish Support

### PR DESCRIPTION
**Pull request by ahmetozantekin**
Well great project.
i added turkish lorem. Some kind of poem.

### CODE REVIEW

**Comment by 3raxton** [comment]
Could you also update the [README](https://github.com/3raxton/ForeignIpsum/blob/master/README.md#swedish-ctrl-alt-shift-command-s) with the Turkish text and it's translation? Cheers!

**Comment by 3raxton** [comment]
If you don't want to add the translation let me know and I will merge it without the addition to the README.

**Comment by ahmetozantekin** [comment]
okay i changed :)

**Comment by 3raxton** [comment]
Awesome! Thank you immensely, I am glad you contributed! Feel free to do so in the future!

**Pull request merged**
